title: 西河某人的游戏屋
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.westriverlin.fun" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 西河某人 # add your name
author-img: myImages/Me.jpg # add your photo
about-author: 我是一名游戏开发者，希望能做出更有趣、更迷人的作品！ # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: WestRiverLin # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: WestRiverLin@QQ.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
